project:
  type: website
  resources: 
    - "files/"

execute: 
  freeze: auto

website:
  title: "stat120"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    contents: 
      - section: Notes
        contents: notes
      - section: Activities
        contents: activities
      - section: Slides
        contents: slides
      - section: Project
        contents: project

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



